### ISSUE TITLE
TypeScript Errors when attempting to run

### ISSUE THREAD

**Issue by snerks** [fakoua/cowsay#3]
**Steps to reproduce**

Windows 10
In terminal (e.g. Git Bash)

``` bash
$ deno run https://deno.land/x/cowsay/cowsay.ts -t="Hello world"
Compile https://deno.land/x/cowsay/cowsay.ts
error: TS7053 [ERROR]: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'typeof import("https://deno.land/x/cowsay/src/balloon")'.
  No index signature with a parameter of type 'string' was found on type 'typeof import("https://deno.land/x/cowsay/src/balloon")'.
 return baloon[action](options.text, options.wrap ? options.wrapLength : null) + "\n" + cow(face);
        ~~~~~~~~~~~~~~
    at https://deno.land/x/cowsay/mod.ts:34:9

TS7053 [ERROR]: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'typeof import("https://deno.land/x/cowsay/src/cows/cows")'.
  No index signature with a parameter of type 'string' was found on type 'typeof import("https://deno.land/x/cowsay/src/cows/cows")'.
 let text = cows[cow]
            ~~~~~~~~~
    at https://deno.land/x/cowsay/src/cows.ts:5:13

TS7006 [ERROR]: Parameter 'options' implicitly has an 'any' type.
 return function (options) {
                  ~~~~~~~
    at https://deno.land/x/cowsay/src/cows.ts:6:19

TS7006 [ERROR]: Parameter 'options' implicitly has an 'any' type.
export const faces = function (options): any {
                               ~~~~~~~
    at https://deno.land/x/cowsay/src/faces.ts:40:32

Found 4 errors.
```

**Comment by fakoua** [comment]
Hi, 
Please add --reload to your cli because we updated the file hours ago:

`deno run --reload https://deno.land/x/cowsay/cowsay.ts -t="Hello world"`

thanks

**Comment by snerks** [comment]
Hi, 

I had just noticed that the TS error messages referred to code that didn't match the source.

Retried, with your suggested `--reload` option. All works fine now!

Thanks
